services:
  odoo:
    container_name: odooApp
    image: odoo:latest
    depends_on:
      - db
    restart: always
    ports:
      - "9001:8069"
      - "9002:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    container_name: postgresdb
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_db
      - POSTGRES_USER=odoo_userdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5501:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data:
  odoo-data:
