# Generated by Django 5.1.5 on 2025-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
