# Generated by Django 5.1.5 on 2025-02-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='id',
            new_name='idCurso',
        ),
    ]
